name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        options:
          - 'apply'
          - 'destroy'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      

    - name: Initialize Terraform
      run: terraform init

    - name: Save Terraform state file
      run: mv terraform.tfstate tfstate_backup/terraform.tfstate
      if: ${{ github.event.inputs.action == 'apply' }}

    - name: Terraform ${{ github.event.inputs.action }}
      run: |
        if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
          terraform apply -auto-approve
        elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
          terraform init
          mv tfstate_backup/terraform.tfstate terraform.tfstate
          terraform destroy -auto-approve
        fi

    # - name: Cleanup
    #   run: rm -rf .terraform

